name: draft_view
description: A draft js renderer written in Dart! You can easily render your draft js object in Flutter!
version: 0.9.2-nullsafety.0
repository: https://github.com/sirily11/flutter_draftview

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
